#!/usr/bin/env python3

import requests

URL = 'https://autochessvng.com/us/load-hero'

for n in range(1, 80):
    r = requests.get(f'{URL}?id={n}')
    with open(f'testing-{n}.html', 'w') as f:
        f.write(r.text)
    print('iteration', n, 'done')
